print(isinstance(10,int))
print(isinstance(10,float))
print(isinstance(1,bool))
print(isinstance(0,bool))
print(isinstance(78.8,int))
print(isinstance(78.8,float))
print(isinstance(78.8,complex))
print(isinstance(True,bool))
